### ISSUE TITLE
Consider using the parser generator of parso

### ISSUE THREAD

**Issue by davidhalter** [yuan-xy/marso#1]
Hey :)

Just saw that you forked/copied parso/jedi. Great that you did :) 

I just wanted to say that it might make sense to not fork everything of parso. Jedi probably needs to be forked, because you want to replace quite a lot of the code there. Feel free to do whatever you want, just letting you know, because sometimes it's easier not to fork things, because then you will have to maintain the full thing.

However parso is a parser generator and you can generate a grammar file for it and a tokenizer to make it work. You can basically just copy the grammar in `parso/python/grammar38.txt` and modify it so it works for your own grammar. The tokenizer is usually a bit more work, but it's usually also not that hard (except for Python, because of the whitespace stuff).

**Comment by yuan-xy** [comment]
Thanks for your kind advices :)

Because I just want to support python 3.6 above and use venv instead of virtualenv and tox, the original codebase is too complex and old. I changed from ruby to python last year. so I'm not familar with python2/tox/virtualenv etc.


发件人: Dave Halter<mailto:notifications@github.com>
发送时间: 2020年5月29日 3:29
收件人: yuan-xy/marso<mailto:marso@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [yuan-xy/marso] Consider using the parser generator of parso (#1)


Hey :)

Just saw that you forked/copied parso/jedi. Great that you did :)

I just wanted to say that it might make sense to not fork everything of parso. Jedi probably needs to be forked, because you want to replace quite a lot of the code there. Feel free to do whatever you want, just letting you know, because sometimes it's easier not to fork things, because then you will have to maintain the full thing.

However parso is a parser generator and you can generate a grammar file for it and a tokenizer to make it work. You can basically just copy the grammar in parso/python/grammar38.txt and modify it so it works for your own grammar. The tokenizer is usually a bit more work, but it's usually also not that hard (except for Python, because of the whitespace stuff).

―
